name = "hourguile"
license = "MIT"
licenselink = "https://github.com/bghost/hourguile/blob/master/LICENSE"
description = "HUGO theme for bghost.xyz"
homepage = "https://github.com/bghost/hourguile"
tags = ["blog", "minimal"]
features = ["blog"]
min_version = "0.41"

[author]
  name = "bghost"
  homepage = "https://bghost.xyz"

[original]
  name = "vimux"
  homepage = "https://github.com/vimux"
