name = "ourguile"
license = "MIT"
licenselink = "https://github.com/bghost/ourguile/blob/master/LICENSE.md"
description = "HUGO theme for bghost.xyz"
homepage = "https://github.com/bghost/hourguile/"
tags = ["blog", "minimal", "dark"]
features = ["blog"]
min_version = 0.17

[author]
  name = "bghost"
  homepage = "https://github.com/bghost"

[original]
  name = "Vimux"
  homepage = "https://github.com/vimux"
